name: setup-enos
description: Setup GitHub CLI, enos, on GitHub Actions runners
inputs:
  version:
    description: Version of Enos CLI to install
    required: false
    default: 0.0.19
runs:
  using: node16
  main: dist/index.js
