name: setup-enos
description: Setup GitHub CLI, enos, on GitHub Actions runners
inputs:
  github-token:
    description: "GitHub token to access the release."
    required: true
  version:
    description: Version of Enos CLI to install
    required: false
    default: '0.0.15'
runs:
  using: node16
  main: dist/index.js
