# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: setup-enos
description: Setup GitHub CLI, enos, on GitHub Actions runners
inputs:
  version:
    description: Version of Enos CLI to install
    required: false
runs:
  using: node20
  main: dist/index.js
