# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
name: Acceptance test of action-setup-enos
description: Verify that the action installs and makes it available

runs:
  using: composite
  steps:
    - id: install
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GH_TOKEN: ${{ github.token }}
      run: |
        version=$(enos version)
        latest=$(gh release view -R hashicorp/enos --json tagName --jq '.tagName')
        if [[ "v${version}" != "${latest}" ]]; then
          echo "Action installed version ${version} when ${latest} is latest!";
          exit 1;
        fi
        dist_version=$(grep "^const latestVersion =" dist/index.js |awk -F"=" '{print $2}' | tr -d " ';" | tr -d '"')
        if [[ "${version}" != "${dist_version}" ]]; then
          echo "dist index.js not updated to latest. Expected: ${version}, got: ${dist_version}";
          exit 1;
        fi
