name: "Tag Release"

on:
  # Run this workflow only when package.json is updated
  push:
    paths:
      - "package.json"
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history
      - name: Setup GitHub User
        run: |
          git config --global user.email "team-vault-quality@hashicorp.com"
          git config --global user.name "Vault Quality Team"
      - name: Tag Release
        run: |
          TAG="v$(jq -r '.version' < package.json)"
          git tag -a -m "$TAG" "$TAG"
          git tag -a -m "$TAG" v1 -f
          git push --tags -f
