name: "Tag Release"

on:
  # Run this workflow only when package.json is updated
  push:
    paths:
      - "package.json"
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history
      - name: Setup GitHub User
        run: |
          git config --global user.email "team-secure-quality@hashicorp.com"
          git config --global user.name "QTI Team"
      - name: Tag Release
        run: |
          TAG="v$(cat package.json| jq -r '.version')"
          git tag -a -m "$TAG" $TAG
          git tag -a -m "$TAG" v1 -f
          git push --tags -f
