---
name: test

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
      - run: npm install
      - name: Run CI checks
        run: npm run ci
      - name: Ensure that we haven't already released version
        run: |
          TAG="$(jq -r ".version" < package.json)"
          if git tag -l | grep -q "v$TAG"; then
            echo "Version $TAG already released, update package.json!";
            exit 1
          fi

  unauthenticated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
      - name: Run action-setup-enos
        uses: ./
      - uses: ./.github/actions/acceptance

  with-github-token-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
      - name: Run action-setup-enos
        with:
          github-token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
        uses: ./
      - uses: ./.github/actions/acceptance

  with-GITHUB_TOKEN-env-var:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
      - name: Run action-setup-enos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
      - uses: ./.github/actions/acceptance
