---
name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: "Validate Action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Run tests"
        run: npm install && npm test

      - name: "Validate Action Exectution"
        uses: hashicorp/action-setup-enos@{{github.GITHUB_SHA}}
        with:
          github-token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
