---
name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: "Validate Action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 16
      - name: "NPM Install"
        run: npm install
      - name: "ESLint"
        run: npm run lint
      - name: "NPM Test"
        run: npm test
      - name: "Validate action installation"
        uses: ./ #this took a full day to figure out and I hate it
        with:
          github-token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
      - name: "Check package.json version is not in released tags"
        run: |
          TAG=$(cat package.json| jq -r ".version")
          if git tag -l | grep -q "v$TAG"; then
            echo "Version $TAG already released, update package.json!";
            exit 1
          fi
      - name: "Check action & latest released versions"
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
        run: |
          version=$(enos version)
          latest=$(gh release view -R hashicorp/enos --json tagName --jq '.tagName')
          if [[ "v${version}" != "${latest}" ]];
          then
            echo "Action installed version ${version} when ${latest} is latest!";
            exit 1;
          fi
      - name: "Check action version matches dist version"
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
        run: |
          version=$(enos version)
          dist_version=$(grep "^const latestVersion =" dist/index.js |awk -F"=" '{print $2}' |tr -d " ';")
          if [[ "${version}" != "${dist_version}" ]];
          then
            echo "dist index.js not updated to latest";
            exit 1;
          fi
